### ISSUE TITLE
No Arm64 support for 0.5.0

### ISSUE THREAD

**Issue by joepio** [quickwit-oss/helm-charts#35]
When setting 

```yaml
image:
  tag: v0.5.0
```

I get

`Failed to pull image "quickwit/quickwit:v0.5.0": rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries`

Setting tag to `latest` fixed the issue.

**Comment by fmassot** [comment]
@joepio I made a mistake, it's `tag: 0.5.0` :/
I was looking at this file https://github.com/quickwit-oss/helm-charts/blob/main/charts/quickwit/Chart.yaml#L6 when I answer you, I don't really know why in the chart yaml you need to add a `v`.

**Comment by fmassot** [comment]
There is also an image tagged `v0.5.0`
https://hub.docker.com/layers/quickwit/quickwit/v0.5.0/images/sha256-177b69df587cf36995c4cc47bad8dead00ce9678c9580a602f8e4d5f7526a983?context=explore

**Comment by joepio** [comment]
Setting to `v0.5.0` or `0.5.0` gives the same error here. 

I also tried some platform settings, yet still the same error

```yml
image:
  # platform: linux/x86_64
  platform: linux/amd64
  tag: 0.5.0
```

**Comment by fmassot** [comment]
The helm chart does not use the platform value. And actually, I don't understand how quickwit can run on your arm instance.
Do you have QEMU installed?

**Comment by fmassot** [comment]
@joepio from 0.5.1 we build a multiarch docker image bother for amd64 and arm64! 

Closing.

**Comment by joepio** [comment]
Awesome, thanks!
