### ISSUE TITLE
add rest labels for v0.7

### ISSUE THREAD

**Issue by tuziben** [quickwit-oss/helm-charts#62]
should add rest labels here https://github.com/quickwit-oss/helm-charts/blob/main/charts/quickwit/templates/configmap.yaml#L13

```
    {{- with .Values.config.rest }}
    rest:
      {{- toYaml . | nindent 6 }}
    {{- end }}
```

**Comment by idrissneumann** [comment]
Hi.

Thanks for the issue.

I think by "rest labels" you're referring to this configuration's section? https://quickwit.io/docs/configuration/node-config#rest-configuration ?

I have opened a pull request here: https://github.com/quickwit-oss/helm-charts/pull/89

Tests in progress :)

**Comment by idrissneumann** [comment]
Tests ok, pr's ready

<img width="964" alt="Screenshot 2024-06-18 at 17 30 07" src="https://github.com/quickwit-oss/helm-charts/assets/12884347/3acfcdd9-dec1-4cd5-a5b2-8cba62df18c4">

**Comment by idrissneumann** [comment]
I think we can close this issue @rdettai @fmassot it has been handled in the #85 which just get merged :)

**Comment by guilload** [comment]
You have free rein to open/close issues on this project as you see fit @idrissneumann.

**Comment by idrissneumann** [comment]
@guilload It doesn't seems to be the case, I can only comment ^^

![Screenshot 2024-06-26 at 13 54 34](https://github.com/quickwit-oss/helm-charts/assets/12884347/f94f1a23-f6af-45b4-9ba0-fd09bc7c9d29)

**Comment by guilload** [comment]
Arf, let me fix this.
