### ISSUE TITLE
Add quickwit to ArtifactHub

### ISSUE THREAD

**Issue by pmig** [quickwit-oss/helm-charts#86]
It seems that is repository is not yet tracked by artifacthub.io. In fact it seems that there are already 2 community packages already present (https://artifacthub.io/packages/search?ts_query_web=quickwit).

Adding a package to artifacthub is super straight forward: You just need to sign-up and than add a `artifacthub-repo.yml` file to your repository.

ArtifactHub will than regularly scan your helm repository for new chart verions. 

The ArtifactHub allows @glasskube to get notified about about new helm chart versions, which will kick off our internal ci/cd pipeline.

**Comment by M0NsTeRRR** [comment]
It was added in 4e12080

**Comment by fmassot** [comment]
indeed! thanks @M0NsTeRRR
