### ISSUE TITLE
Feature Request: Add Support for initContainers in Helm charts for all deployable components

### ISSUE THREAD

**Issue by hgudladona** [quickwit-oss/helm-charts#91]
We request to add add Support for initContainers in Helm charts for all deployable components. This can help in use cases such as templating the node configuration and use the init container to substitute some values in the config file and use the mutated file as the config source for the quickwit components. 

We are working on a PR to propose this.

**Comment by idrissneumann** [comment]
PR #92 merged, we can close :)

Thanks for your work
