### ISSUE TITLE
Merge jobs top level section with bootstrap section

### ISSUE THREAD

**Issue by idrissneumann** [quickwit-oss/helm-charts#98]
Following this comment from @rdettai : https://github.com/quickwit-oss/helm-charts/pull/95#issuecomment-2249826979

We're opening this issue in order to move the `jobs` top level section content (`extraVolumes`, `extraVolumeMounts` and `initContainers`) into the `bootstrap` section.

It'll be a breaking change, so to version and document in the README.

**Comment by fmassot** [comment]
+1 indeed

**Comment by idrissneumann** [comment]
PR opened and tested on kind: #99
